import { x25519 } from '@noble/curves/ed25519';

/**
 * X25519 keypair generation, public-key derivation, and Diffie-Hellman.
 *
 * Backed by @noble/curves rather than libsodium because
 * `react-native-libsodium` does not expose `crypto_kx_*` or
 * `crypto_scalarmult*` to JSI. Calling those on device produced
 * "undefined is not a function" at the first pairing attempt. The wire
 * format is identical (RFC 7748 X25519), so this swap is
 * byte-compatible with any persisted keys or peer pubkeys generated by
 * the libsodium-backed Node path.
 */

export interface X25519KeyPair {
  publicKey: Uint8Array;
  privateKey: Uint8Array;
}

const X25519_KEY_BYTES = 32;

export async function generateX25519KeyPair(): Promise<X25519KeyPair> {
  const privateKey = x25519.utils.randomPrivateKey();
  const publicKey = x25519.getPublicKey(privateKey);
  return { publicKey, privateKey };
}

export async function x25519PublicKey(privateKey: Uint8Array): Promise<Uint8Array> {
  if (privateKey.length !== X25519_KEY_BYTES) {
    throw new Error(`x25519 private key must be ${X25519_KEY_BYTES} bytes`);
  }
  return x25519.getPublicKey(privateKey);
}

export async function x25519DH(
  privateKey: Uint8Array,
  peerPublicKey: Uint8Array,
): Promise<Uint8Array> {
  if (privateKey.length !== X25519_KEY_BYTES) {
    throw new Error(`x25519 private key must be ${X25519_KEY_BYTES} bytes`);
  }
  if (peerPublicKey.length !== X25519_KEY_BYTES) {
    throw new Error(`x25519 public key must be ${X25519_KEY_BYTES} bytes`);
  }
  return x25519.getSharedSecret(privateKey, peerPublicKey);
}
