import { x25519 } from '@noble/curves/ed25519';

import { getSodium } from './sodium.js';

/**
 * X25519 keypair generation, public-key derivation, and Diffie-Hellman.
 *
 * Curve math is backed by @noble/curves rather than libsodium because
 * `react-native-libsodium` does not expose `crypto_kx_*` or
 * `crypto_scalarmult*` to JSI. Calling those on device produced
 * "undefined is not a function" at the first pairing attempt. The wire
 * format is identical (RFC 7748 X25519), so this swap is
 * byte-compatible with any persisted keys or peer pubkeys generated by
 * the libsodium-backed Node path.
 *
 * Randomness for keygen comes from libsodium's `randombytes_buf`, NOT
 * from noble's `x25519.utils.randomPrivateKey()`. Noble's helper pulls
 * entropy from the Web Crypto `crypto.getRandomValues`, which Hermes does
 * not provide — so the noble path threw at the first keypair on device and
 * left the QR screen hung on "Preparing your pairing QR…". Every other
 * primitive in this package already sources entropy from libsodium's
 * native CSPRNG (AEAD nonces, Safe Word salts, the device master key at
 * boot), so reusing it here keeps a single, already-proven entropy source
 * instead of adding a Web Crypto polyfill. A raw 32-byte secret is a valid
 * X25519 private scalar; noble clamps it per RFC 7748 inside
 * `getPublicKey`/`getSharedSecret`, so the result is identical to what
 * `randomPrivateKey()` would have produced.
 */

export interface X25519KeyPair {
  publicKey: Uint8Array;
  privateKey: Uint8Array;
}

const X25519_KEY_BYTES = 32;

export async function generateX25519KeyPair(): Promise<X25519KeyPair> {
  const sodium = await getSodium();
  const privateKey = sodium.randombytes_buf(X25519_KEY_BYTES);
  const publicKey = x25519.getPublicKey(privateKey);
  return { publicKey, privateKey };
}

export async function x25519PublicKey(privateKey: Uint8Array): Promise<Uint8Array> {
  if (privateKey.length !== X25519_KEY_BYTES) {
    throw new Error(`x25519 private key must be ${X25519_KEY_BYTES} bytes`);
  }
  return x25519.getPublicKey(privateKey);
}

export async function x25519DH(
  privateKey: Uint8Array,
  peerPublicKey: Uint8Array,
): Promise<Uint8Array> {
  if (privateKey.length !== X25519_KEY_BYTES) {
    throw new Error(`x25519 private key must be ${X25519_KEY_BYTES} bytes`);
  }
  if (peerPublicKey.length !== X25519_KEY_BYTES) {
    throw new Error(`x25519 public key must be ${X25519_KEY_BYTES} bytes`);
  }
  return x25519.getSharedSecret(privateKey, peerPublicKey);
}
